# Generated by Django 5.2 on 2025-04-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='usuario_temp', max_length=100)),
                ('email', models.EmailField(default='temp@email.com', max_length=254)),
                ('senha', models.CharField(default='senha123', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título não informado', max_length=100)),
                ('diretor', models.CharField(default='Diretor não informado', max_length=100)),
                ('ano', models.IntegerField(default=1900)),
                ('genero', models.CharField(default='Gênero não informado', max_length=50)),
            ],
        ),
    ]
