# Generated by Django 5.1.7 on 2025-04-04 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='usuario_temp', max_length=100)),
                ('email', models.EmailField(default='temp@email.com', max_length=254)),
                ('senha', models.CharField(default='senha123', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título não informado', max_length=100)),
                ('diretor', models.CharField(default='Diretor não informado', max_length=100)),
                ('ano', models.IntegerField(default=1900)),
                ('genero', models.CharField(default='Gênero não informado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_favoritado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.filmes')),
            ],
            options={
                'unique_together': {('usuario', 'filme')},
            },
        ),
    ]
