# Generated by Django 5.2 on 2025-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeBD', models.TextField(blank=True, null=True)),
                ('emailBD', models.EmailField(blank=True, max_length=254, null=True)),
                ('senhaBD', models.TextField(blank=True, null=True)),
                ('confirmarSenhaBD', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
