# Generated by Django 5.2 on 2025-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFilmeBD', models.TextField(blank=True, null=True)),
                ('diretorFilmeBD', models.TextField(blank=True, null=True)),
                ('anoFilmeBD', models.IntegerField(blank=True, null=True)),
                ('generoFilmeBD', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CadastroAdmin',
            new_name='Cadastro',
        ),
    ]
