# Generated by Django 5.1.7 on 2025-04-04 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFilmeBD', models.TextField(blank=True, null=True)),
                ('diretorFilmeBD', models.TextField(blank=True, null=True)),
                ('anoFilmeBD', models.IntegerField(blank=True, null=True)),
                ('generoFilmeBD', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CadastroAdmin',
            new_name='Cadastro',
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_favoritado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicativo.filmes')),
            ],
            options={
                'unique_together': {('usuario', 'filme')},
            },
        ),
    ]
