# Generated by Django 5.2 on 2025-04-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0002_filmes_rename_cadastroadmin_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='confirmarSenhaBD',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='emailBD',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='nomeBD',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='senhaBD',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='anoFilmeBD',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='diretorFilmeBD',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='generoFilmeBD',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='nomeFilmeBD',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(default='temp@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(default='usuario_temp', max_length=100),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(default='senha123', max_length=100),
        ),
        migrations.AddField(
            model_name='filmes',
            name='ano',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='filmes',
            name='diretor',
            field=models.CharField(default='Diretor Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='filmes',
            name='genero',
            field=models.CharField(default='Indefinido', max_length=50),
        ),
        migrations.AddField(
            model_name='filmes',
            name='nome',
            field=models.CharField(default='Filme Temporário', max_length=100),
        ),
    ]
