# Generated by Django 5.2 on 2025-04-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0003_remove_cadastro_confirmarsenhabd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmes',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='diretor',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='nome',
        ),
        migrations.AddField(
            model_name='filmes',
            name='anoFilmeInsert',
            field=models.IntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='filmes',
            name='diretorFilmeInsert',
            field=models.CharField(default='Diretor não informado', max_length=100),
        ),
        migrations.AddField(
            model_name='filmes',
            name='generoFilmeInsert',
            field=models.CharField(default='Gênero não informado', max_length=50),
        ),
        migrations.AddField(
            model_name='filmes',
            name='nomeFilmeInsert',
            field=models.CharField(default='Título não informado', max_length=100),
        ),
    ]
