# Generated by Django 5.2 on 2025-04-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0003_filmes_favoritado_por_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorito',
            name='favorito',
        ),
        migrations.RemoveField(
            model_name='filmes',
            name='favoritado_por',
        ),
    ]
