# Generated by Django 5.2 on 2025-04-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0004_remove_filmes_ano_remove_filmes_diretor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmes',
            old_name='anoFilmeInsert',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='filmes',
            old_name='diretorFilmeInsert',
            new_name='diretor',
        ),
        migrations.RenameField(
            model_name='filmes',
            old_name='generoFilmeInsert',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='filmes',
            old_name='nomeFilmeInsert',
            new_name='titulo',
        ),
    ]
