# Generated by Django 5.2 on 2025-04-24 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0004_remove_favorito_favorito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorito',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 24, 16, 57, 10, 152288, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
