# Generated by Django 5.1.7 on 2025-04-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0005_favorito_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='sinopse',
            field=models.TextField(default='Sinopse não informada.'),
        ),
        migrations.AddField(
            model_name='filmes',
            name='tipo',
            field=models.CharField(choices=[('live-action', 'Live Action'), ('animacao', 'Animação')], default='Live Action', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmes',
            name='genero',
            field=models.CharField(choices=[('acao', 'Ação'), ('terror', 'Terror'), ('comedia', 'Comédia'), ('ficcao-cientifica', 'Ficção Científica'), ('romance', 'Romance'), ('heroi', 'Herói'), ('suspense', 'Suspense'), ('drama', 'Drama'), ('aventura', 'Aventura'), ('historia', 'História'), ('documentario', 'Documentário'), ('guerra', 'Guerra'), ('fantasia', 'Fantasia'), ('biografia', 'Biografia'), ('esporte', 'Esporte')], max_length=50),
        ),
    ]
