# Generated by Django 5.2 on 2025-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicativo', '0006_filmes_sinopse_filmes_tipo_alter_filmes_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='cartaz',
            field=models.ImageField(default='cartaz.jpg', upload_to='imagens/'),
        ),
    ]
